apiVersion: v1
kind: Service
metadata:
  name: couchdb2
spec:
  selector:
    app: couchdb2
    tier: database
  ports:
    - protocol: TCP
      targetPort: couchdb2-port
      port: 6984
      name: couchdb2-port
  type: ClusterIP