
apiVersion: v1
kind: Service
metadata:
  name: orderer3
spec:
  selector:
    app: orderer3
    tier: backend
  ports:
  - protocol: TCP
    targetPort: orderer-port
    port: 30070
    nodePort: 30070
    name: orderer-port
  type: NodePort