apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb2
  template:
    metadata:
      labels:
        app: couchdb2
        tier: database
        track: stable
    spec:
      containers:
        - name: couchdb2
          image: "hyperledger/fabric-couchdb"
          env:
            - name: COUCHDB_USER
              value: ""
            - name: COUCHDB_PASSWORD
              value: ""
          ports:
            - name: couchdb2-port
              containerPort: 5984