
apiVersion: v1
kind: Service
metadata:
  name: orderer1
spec:
  selector:
    app: orderer1
    tier: backend
  ports:
  - protocol: TCP
    targetPort: orderer-port
    port: 30050
    nodePort: 30050
    name: orderer-port
  type: NodePort