
apiVersion: v1
kind: Service
metadata:
  name: orderer2
spec:
  selector:
    app: orderer2
    tier: backend
  ports:
  - protocol: TCP
    targetPort: orderer-port
    port: 30060
    nodePort: 30060
    name: orderer-port
  type: NodePort