apiVersion: v1
kind: Service
metadata:
   name: ca-company1
spec:
 selector:
   app: ca-company1
   tier: identity
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 7054
     targetPort: 7054
     nodePort: 30054